-- TeluAI PostgreSQL schema is created by SQLAlchemy in app/database.py.
-- Language data is seeded from data/melimi_seed.json on first initialization.
-- Runtime tables include users, chats, learning, and Melimi language data.
-- Future schema changes should increment SCHEMA_VERSION and use explicit migrations.
