from __future__ import annotations

from sqlalchemy import inspect, text

MIGRATIONS = [
    (1, (
        "CREATE INDEX IF NOT EXISTS ix_conversations_user_updated ON conversations (user_id, updated_at)",
        "CREATE INDEX IF NOT EXISTS ix_messages_conversation_created ON messages (conversation_id, created_at)",
        "CREATE INDEX IF NOT EXISTS ix_learning_candidates_status_created ON learning_candidates (status, created_at)",
        "CREATE INDEX IF NOT EXISTS ix_knowledge_entries_status_kind ON knowledge_entries (status, kind)",
        "CREATE INDEX IF NOT EXISTS ix_melimi_roots_status_updated ON melimi_roots (status, updated_at)",
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_created_action ON audit_logs (created_at, action)",
        "CREATE INDEX IF NOT EXISTS ix_usage_user_created ON usage (user_id, created_at)",
        "CREATE INDEX IF NOT EXISTS ix_user_memory_user_created ON user_memory (user_id, created_at)",
    )),
    (2, (
        "ALTER TABLE learning_candidates ADD COLUMN reviewer_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL",
        "ALTER TABLE learning_candidates ADD COLUMN review_note TEXT DEFAULT ''",
        "CREATE INDEX IF NOT EXISTS ix_learning_candidates_reviewer ON learning_candidates (reviewer_user_id)",
    )),
    (4, (
        """CREATE TABLE IF NOT EXISTS teluai_global_learning (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kind VARCHAR(30) NOT NULL,
            learning_key VARCHAR(255) NOT NULL,
            learning_value TEXT NOT NULL,
            source VARCHAR(120) NOT NULL,
            source_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
            evidence TEXT NOT NULL DEFAULT '',
            status VARCHAR(30) NOT NULL DEFAULT 'active',
            version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(kind, learning_key)
        )""",
        "CREATE INDEX IF NOT EXISTS ix_teluai_global_learning_key ON teluai_global_learning (learning_key)",
        "CREATE INDEX IF NOT EXISTS ix_teluai_global_learning_status_kind ON teluai_global_learning (status, kind)",
        "CREATE INDEX IF NOT EXISTS ix_teluai_global_learning_source_user ON teluai_global_learning (source_user_id)",
    )),
]


def _column_exists(conn, table: str, column: str) -> bool:
    return any(item["name"] == column for item in inspect(conn).get_columns(table))


def _table_exists(conn, table: str) -> bool:
    return inspect(conn).has_table(table)


def _upgrade_global_learning_identity(conn) -> None:
    """Upgrade the legacy shared-learning integer key on PostgreSQL.

    Older deployments created `id INTEGER PRIMARY KEY` and supplied MAX(id)+1
    from application code. New deployments may already use a PostgreSQL
    identity column. Identity columns manage their own default sequence and
    reject `ALTER COLUMN ... SET DEFAULT`, so they must be left untouched.
    """
    if conn.dialect.name != "postgresql" or not _table_exists(conn, "teluai_global_learning"):
        return

    identity = conn.execute(text("""
        SELECT is_identity
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'teluai_global_learning'
          AND column_name = 'id'
    """)).scalar()
    if identity == "YES":
        return

    conn.execute(text("CREATE SEQUENCE IF NOT EXISTS teluai_global_learning_id_seq"))
    conn.execute(text("""
        SELECT setval(
            'teluai_global_learning_id_seq',
            COALESCE((SELECT MAX(id) FROM teluai_global_learning), 0) + 1,
            false
        )
    """))
    conn.execute(text(
        "ALTER TABLE teluai_global_learning "
        "ALTER COLUMN id SET DEFAULT nextval('teluai_global_learning_id_seq')"
    ))
    conn.execute(text(
        "ALTER SEQUENCE teluai_global_learning_id_seq "
        "OWNED BY teluai_global_learning.id"
    ))


def _apply_registered_migrations(engine):
    with engine.begin() as conn:
        conn.execute(
            text(
                "CREATE TABLE IF NOT EXISTS schema_migrations "
                "(version INTEGER PRIMARY KEY, applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"
            )
        )
        applied = {row[0] for row in conn.execute(text("SELECT version FROM schema_migrations"))}
        for version, statements in MIGRATIONS:
            if version in applied:
                continue
            for statement in statements:
                if version == 2 and statement.startswith("ALTER TABLE learning_candidates ADD COLUMN reviewer_user_id"):
                    if _column_exists(conn, "learning_candidates", "reviewer_user_id"):
                        continue
                if version == 2 and statement.startswith("ALTER TABLE learning_candidates ADD COLUMN review_note"):
                    if _column_exists(conn, "learning_candidates", "review_note"):
                        continue
                # Version 4 is deliberately PostgreSQL-first. SQLite test
                # databases already create the compatibility table lazily in
                # teluai2_learning for isolated unit tests.
                if version == 4 and conn.dialect.name != "postgresql":
                    if statement.startswith("CREATE TABLE"):
                        statement = statement.replace(
                            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                            "id INTEGER PRIMARY KEY AUTOINCREMENT",
                        ).replace(
                            "source_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT",
                            "source_user_id INTEGER NOT NULL",
                        )
                conn.execute(text(statement))
            conn.execute(
                text("INSERT INTO schema_migrations(version) VALUES (:version)"),
                {"version": version},
            )
        _upgrade_global_learning_identity(conn)
        conn.execute(
            text("INSERT INTO schema_migrations(version) VALUES (3) ON CONFLICT(version) DO NOTHING")
        )


def run_migrations():
    """Create/update database schema only.

    Runtime route registration, middleware composition and application wiring
    belong to the ASGI composition boundary, not the migration layer.
    """
    from app.database import Base, engine, UserSetting

    Base.metadata.create_all(engine)
    _apply_registered_migrations(engine)
    try:
        UserSetting.__table__.c.preferred_mode.default.arg = "auto"
    except Exception:
        pass
