"""Scoped Telugu language learning extracted from explicit chat suggestions."""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from sqlalchemy import select, text
from app.database import SessionLocal, User, UserMemory, engine, now

TELUGU = r"[\u0C00-\u0C7F]"
WORD = rf"{TELUGU}+(?:{TELUGU}+)*"
GLOBAL_TABLE = "teluai_global_learning"
MAX_VOCAB_LENGTH = 160
MAX_GRAMMAR_LENGTH = 4000
MAX_EVIDENCE_LENGTH = 50000

@dataclass(frozen=True)
class LearningSuggestion:
    kind: str
    key: str
    value: str
    source: str

def _ensure_global_table() -> None:
    id_definition = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine.dialect.name == "postgresql" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    with engine.begin() as db:
        db.execute(text(f"""CREATE TABLE IF NOT EXISTS {GLOBAL_TABLE} (
            id {id_definition}, kind VARCHAR(30) NOT NULL, learning_key VARCHAR(255) NOT NULL,
            learning_value TEXT NOT NULL, source VARCHAR(120) NOT NULL, source_user_id INTEGER NOT NULL,
            evidence TEXT NOT NULL DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(kind, learning_key))"""))
        db.execute(text(f"CREATE INDEX IF NOT EXISTS ix_{GLOBAL_TABLE}_key ON {GLOBAL_TABLE}(learning_key)"))

def _is_global_role(role: str) -> bool:
    return str(role or "").strip().lower() in {"owner", "admin"}

def _clean(value: str) -> str:
    return " ".join(str(value).strip().split()).strip(" .,:;!?\"'()[]{}")

def _valid_suggestion(suggestion: LearningSuggestion) -> bool:
    kind, key, value, source = str(suggestion.kind or "").strip().upper(), _clean(suggestion.key), _clean(suggestion.value), _clean(suggestion.source)
    if kind not in {"VOCABULARY", "GRAMMAR"} or not key or not value or not source or key == value: return False
    if kind == "VOCABULARY":
        if len(key) > MAX_VOCAB_LENGTH or len(value) > MAX_VOCAB_LENGTH: return False
        if not re.fullmatch(WORD, key, flags=re.UNICODE) or not re.fullmatch(WORD, value, flags=re.UNICODE): return False
    elif len(value) > MAX_GRAMMAR_LENGTH: return False
    return len(source) <= MAX_EVIDENCE_LENGTH

def extract_suggestions(text: str) -> list[LearningSuggestion]:
    text = str(text or "").strip()
    if not text: return []
    found: list[LearningSuggestion] = []
    patterns = [
        rf"(?P<standard>{WORD})\s*(?:=|అంటే|అనగా)\s*(?P<telugu>{WORD})",
        rf"(?P<standard>{WORD})\s*(?:కి|కు)?\s*బదులు\s*(?P<telugu>{WORD})\s*(?:వాడాలి|వాడండి|చెప్పాలి|అనాలి)",
        rf"(?:మేలిమి|మెలిమి)(?:\s*తెలుగు)?(?:లో)?\s*(?P<standard>{WORD})\s*(?:అంటే|అనగా|అంటారు|అనాలి)\s*(?P<telugu>{WORD})",
        rf"(?P<standard>{WORD})\s*(?:ను|ని)?\s*(?:మేలిమి|మెలిమి)(?:\s*తెలుగు)?(?:లో)?\s*(?:గా|లో)?\s*(?:<|=|అంటే|అనగా)\s*(?P<telugu>{WORD})",
    ]
    for pattern in patterns:
        for match in re.finditer(pattern, text, flags=re.UNICODE):
            candidate = LearningSuggestion("VOCABULARY", _clean(match.group("standard")), _clean(match.group("telugu")), _clean(match.group(0)))
            if _valid_suggestion(candidate) and candidate not in found: found.append(candidate)
    grammar_patterns = [
        r"(?:మేలిమి|మెలిమి)(?:\s*తెలుగు)?\s*(?:వ్యాకరణ(?:ం|ము)?|నియమం)\s*[:：-]\s*(.+)",
        r"(?:వ్యాకరణంగా|వ్యాకరణంలో)\s*(.+?)\s*(?:అని|అలా)?\s*(?:వాడాలి|చెప్పాలి|ఉంటుంది)[.]?$",
        r"(?:ఇక్కడ|ఈ సందర్భంలో)\s*(.+?)\s*(?:వాడాలి|చెప్పాలి)\s*(?:అని|\.|$)",
    ]
    for pattern in grammar_patterns:
        match = re.search(pattern, text, flags=re.UNICODE)
        if match:
            candidate = LearningSuggestion("GRAMMAR", "rule", _clean(match.group(1)), _clean(match.group(0)))
            if _valid_suggestion(candidate): found.append(candidate); break
    return found

def extract_suggestion(text: str) -> LearningSuggestion | None:
    return (extract_suggestions(text) or [None])[0]

def _role_for_user(user_id: int) -> str:
    with SessionLocal() as db:
        user = db.get(User, int(user_id))
        return str(getattr(user, "role", "user") or "user") if user else "user"

def remember_suggestion(user_id: int, suggestion: LearningSuggestion, role: str | None = None) -> bool:
    if not _valid_suggestion(suggestion): return False
    resolved_role = _role_for_user(user_id) if role is None else str(role)
    if _is_global_role(resolved_role):
        _ensure_global_table()
        with engine.begin() as db:
            db.execute(text(f"""INSERT INTO {GLOBAL_TABLE}
                (kind, learning_key, learning_value, source, source_user_id, evidence)
                VALUES (:kind, :learning_key, :learning_value, :source, :source_user_id, :evidence)
                ON CONFLICT(kind, learning_key) DO UPDATE SET learning_value=excluded.learning_value,
                source=excluded.source, source_user_id=excluded.source_user_id, evidence=excluded.evidence,
                updated_at=CURRENT_TIMESTAMP"""), {"kind": suggestion.kind, "learning_key": suggestion.key,
                "learning_value": suggestion.value, "source": "owner_chat" if str(resolved_role).lower() == "owner" else "approved_admin_chat",
                "source_user_id": int(user_id), "evidence": suggestion.source[:MAX_EVIDENCE_LENGTH]})
        return True
    key = f"telugu_chat_learning:{suggestion.kind}:{suggestion.key}"
    payload = json.dumps({"kind": suggestion.kind, "key": suggestion.key, "value": suggestion.value, "source": suggestion.source}, ensure_ascii=False)
    with SessionLocal() as db:
        row = db.scalar(select(UserMemory).where((UserMemory.user_id == user_id) & (UserMemory.key == key)))
        if row: row.value = payload
        else: db.add(UserMemory(user_id=user_id, key=key, value=payload, created_at=now()))
        db.commit()
    return True

def learned_global(limit: int = 80) -> list[dict[str, str]]:
    _ensure_global_table()
    with engine.begin() as db:
        rows = db.execute(text(f"SELECT kind, learning_key, learning_value, source FROM {GLOBAL_TABLE} ORDER BY updated_at DESC, id DESC LIMIT :limit"), {"limit": max(1, min(int(limit), 200))}).mappings().all()
    return [{"kind": str(r["kind"]), "key": str(r["learning_key"]), "value": str(r["learning_value"]), "source": str(r["source"])} for r in rows]

def learned_for_user(user_id: int, limit: int = 40) -> list[dict[str, str]]:
    with SessionLocal() as db:
        rows = db.scalars(select(UserMemory).where((UserMemory.user_id == user_id) & (UserMemory.key.like("telugu_chat_learning:%"))).order_by(UserMemory.created_at.desc()).limit(max(1, min(limit, 100)))).all()
    result = []
    for row in rows:
        try:
            item = json.loads(row.value)
            if isinstance(item, dict) and item.get("kind") and item.get("value"): result.append({str(k): str(v) for k, v in item.items()})
        except (TypeError, json.JSONDecodeError): pass
    return result

# Retrieval normalization only: it never rewrites user text and never creates a lexical rule.
# These are conservative surface endings that may attach to a learned Telugu lexical item.
_CASE_SUFFIXES = ("యొక్క", "తోటి", "చేత", "వల్ల", "లోని", "గూర్చి", "గురించి", "నుండి", "కోసం", "గురించి", "లను", "లతో", "లలో", "లకు", "లకి", "లని", "లతో", "ను", "ని", "కు", "కి", "తో", "లో", "న", "యై")

def _normalize_telugu_term(term: str) -> str:
    value = str(term or "").strip().casefold()
    for suffix in sorted(_CASE_SUFFIXES, key=len, reverse=True):
        if len(value) > len(suffix) + 1 and value.endswith(suffix):
            return value[:-len(suffix)]
    if len(value) > 3 and value.endswith("లు"): return value[:-2]
    return value

def _relevance_forms(term: str) -> set[str]:
    value = str(term or "").strip().casefold()
    normalized = _normalize_telugu_term(value)
    forms = {value}
    if normalized and normalized != value: forms.add(normalized)
    return forms

def _relevance_terms(message: str) -> set[str]:
    raw = re.findall(r"[\u0C00-\u0C7F]{1,}|[A-Za-z]{3,}", str(message or ""), flags=re.UNICODE)
    terms = set()
    for term in raw: terms.update(_relevance_forms(term))
    return terms

def _is_relevant(item: dict[str, str], terms: set[str]) -> bool:
    if not terms: return False
    haystack = " ".join((item.get("key", ""), item.get("value", ""))).casefold()
    haystack_forms = set()
    for token in re.findall(r"[\u0C00-\u0C7F]{1,}|[A-Za-z]{3,}", haystack, flags=re.UNICODE): haystack_forms.update(_relevance_forms(token))
    return bool(terms.intersection(haystack_forms))

def _append_learning_guidance(lines: list[str], item: dict[str, str]) -> None:
    if item.get("kind") == "VOCABULARY":
        lines.append(f"- పద వినియోగ సూచన: {item.get('key', '')} → {item.get('value', '')}")
        lines.append("  ఇది యజమాని/ఆమోదిత నిర్వాహకుల స్పష్టమైన భాషా జ్ఞానం. సంబంధిత సందర్భంలో సహజంగా ఉపయోగించు; సంబంధం లేని సందర్భంలో బలవంతంగా వర్తింపజేయవద్దు; కల్పిత పదం సృష్టించవద్దు.")
    elif item.get("kind") == "GRAMMAR": lines.append(f"- వ్యాకరణ సూచన: {item.get('value', '')}")

def prompt_context(user_id: int, role: str = "user", message: str = "") -> str:
    terms = _relevance_terms(message)
    global_items, private_items = learned_global(limit=80), learned_for_user(user_id, limit=40)
    relevant_global = [item for item in global_items if _is_relevant(item, terms)][:12] if terms else global_items[:8]
    relevant_private = [item for item in private_items if _is_relevant(item, terms)][:8] if terms else private_items[:8]
    if not relevant_global and not relevant_private: return ""
    lines = []
    if relevant_global:
        lines.append("సందర్భానికి సంబంధించిన భాగస్వామ్య మేలిమి తెలుగు జ్ఞానం (యజమాని/ఆమోదిత నిర్వాహకుల స్పష్టమైన సూచనల నుంచి):")
        for item in reversed(relevant_global): _append_learning_guidance(lines, item)
        lines.append("ఈ జ్ఞానాన్ని సంబంధిత సందర్భంలో మాత్రమే ఉపయోగించు; ఇది అధికారికంగా ఆమోదించబడిన భాషా జ్ఞానం.")
    if relevant_private:
        lines.append("ఈ వినియోగదారుడి వ్యక్తిగత తెలుగు భాషా జ్ఞాపకాలు:")
        for item in reversed(relevant_private): _append_learning_guidance(lines, item)
        lines.append("ఇవి ఈ వినియోగదారుడి వ్యక్తిగత సూచనలు. ఇతర వినియోగదారులకు వర్తింపజేయవద్దు.")
    if terms:
        lines.append("ప్రస్తుత సందేశంలోని పదం నేర్చుకున్న పదానికి విభక్తి/బహువచన రూపాంతరం అయితే, దాన్ని మూల పదంతో అనుసంధానించి అర్థం చేసుకో.")
    return "\n".join(lines)
