"""TEX-L: trusted Melimi research and approval service."""
from __future__ import annotations

from sqlalchemy import text
from app.database import engine
from app.teluai2_learning import LearningSuggestion, _valid_suggestion, remember_suggestion, learned_global, extract_suggestions

TABLE = "teluai_texl_pending"


def ensure_table() -> None:
    identity = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine.dialect.name == "postgresql" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    with engine.begin() as db:
        db.execute(text(f"""CREATE TABLE IF NOT EXISTS {TABLE} (
            id {identity}, kind VARCHAR(30) NOT NULL, learning_key VARCHAR(255) NOT NULL,
            learning_value TEXT NOT NULL, evidence TEXT NOT NULL DEFAULT '', status VARCHAR(20) NOT NULL DEFAULT 'pending',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )"""))
        db.execute(text(f"CREATE INDEX IF NOT EXISTS ix_{TABLE}_status ON {TABLE}(status)"))


def _row(row) -> dict:
    return {"id": int(row["id"]), "kind": str(row["kind"]), "key": str(row["learning_key"]), "value": str(row["learning_value"]), "evidence": str(row["evidence"] or ""), "status": str(row["status"]), "created_at": str(row["created_at"]), "updated_at": str(row["updated_at"])}


def pending(limit: int = 200) -> list[dict]:
    ensure_table()
    with engine.begin() as db:
        rows = db.execute(text(f"SELECT * FROM {TABLE} WHERE status='pending' ORDER BY id DESC LIMIT :limit"), {"limit": max(1, min(int(limit), 500))}).mappings().all()
    return [_row(x) for x in rows]


def all_learned() -> dict:
    ensure_table()
    with engine.begin() as db:
        rows = db.execute(text(f"SELECT * FROM {TABLE} ORDER BY id DESC LIMIT 500")).mappings().all()
    return {"approved": learned_global(limit=200), "pending": [_row(x) for x in rows if x["status"] == "pending"], "rejected": [_row(x) for x in rows if x["status"] == "rejected"]}


def propose(suggestion: LearningSuggestion) -> dict | None:
    if not _valid_suggestion(suggestion):
        return None
    ensure_table()
    with engine.begin() as db:
        existing = db.execute(text(f"SELECT id FROM {TABLE} WHERE kind=:kind AND learning_key=:key AND status='pending'"), {"kind": suggestion.kind, "key": suggestion.key}).first()
        if existing:
            row = db.execute(text(f"SELECT * FROM {TABLE} WHERE id=:id"), {"id": existing[0]}).mappings().first()
            return _row(row) if row else None
        row = db.execute(text(f"""INSERT INTO {TABLE}(kind,learning_key,learning_value,evidence,status) VALUES(:kind,:key,:value,:evidence,'pending') RETURNING id,kind,learning_key,learning_value,evidence,status,created_at,updated_at"""), {"kind": suggestion.kind, "key": suggestion.key, "value": suggestion.value, "evidence": suggestion.source}).mappings().first()
    return _row(row) if row else None


def propose_from_text(text_value: str) -> list[dict]:
    result = []
    for suggestion in extract_suggestions(text_value):
        item = propose(suggestion)
        if item:
            result.append(item)
    return result


def approve(item_id: int, reviewer_user_id: int, role: str = "owner", key: str | None = None, value: str | None = None) -> dict:
    trusted_role = str(role or "").lower()
    if trusted_role not in {"owner", "admin"}:
        raise ValueError("Trusted reviewer permission required.")
    ensure_table()
    with engine.begin() as db:
        row = db.execute(text(f"SELECT * FROM {TABLE} WHERE id=:id AND status='pending'"), {"id": int(item_id)}).mappings().first()
    if not row:
        raise ValueError("Pending TEX-L item not found.")
    final_key = str(key if key is not None else row["learning_key"]).strip()
    final_value = str(value if value is not None else row["learning_value"]).strip()
    evidence = str(row["evidence"] or "")
    suggestion = LearningSuggestion(str(row["kind"]), final_key, final_value, evidence)
    if not _valid_suggestion(suggestion):
        raise ValueError("Edited learning is invalid.")
    if not remember_suggestion(reviewer_user_id, suggestion, role=trusted_role):
        raise ValueError("Could not approve learning.")
    with engine.begin() as db:
        db.execute(text(f"UPDATE {TABLE} SET learning_key=:key,learning_value=:value,status='approved',updated_at=CURRENT_TIMESTAMP WHERE id=:id"), {"id": int(item_id), "key": final_key, "value": final_value})
    return {"id": int(item_id), "kind": suggestion.kind, "key": final_key, "value": final_value, "status": "approved", "reviewer_role": trusted_role, "reviewer_user_id": int(reviewer_user_id)}


def reject(item_id: int) -> bool:
    ensure_table()
    with engine.begin() as db:
        result = db.execute(text(f"UPDATE {TABLE} SET status='rejected',updated_at=CURRENT_TIMESTAMP WHERE id=:id AND status='pending'"), {"id": int(item_id)})
    return result.rowcount > 0


def approve_all(reviewer_user_id: int, role: str = "owner") -> int:
    count = 0
    for item in list(pending(500)):
        approve(item["id"], reviewer_user_id, role=role)
        count += 1
    return count
